// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Message
	Path
	Flow
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Path_ConnectorType int32

const (
	Path_HTTP   Path_ConnectorType = 0
	Path_MQTT   Path_ConnectorType = 1
	Path_KAFKA  Path_ConnectorType = 2
	Path_LAMBDA Path_ConnectorType = 3
)

var Path_ConnectorType_name = map[int32]string{
	0: "HTTP",
	1: "MQTT",
	2: "KAFKA",
	3: "LAMBDA",
}
var Path_ConnectorType_value = map[string]int32{
	"HTTP":   0,
	"MQTT":   1,
	"KAFKA":  2,
	"LAMBDA": 3,
}

func (x Path_ConnectorType) String() string {
	return proto.EnumName(Path_ConnectorType_name, int32(x))
}
func (Path_ConnectorType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// Message is passed between connectors and Conduction
// A Message should not have origin AND destination. Origin will be in Messages from connectors to Conduction and destination will be from Conduction to connectors
type Message struct {
	Origin      *Path             `protobuf:"bytes,1,opt,name=origin" json:"origin,omitempty"`
	Return      *Path             `protobuf:"bytes,2,opt,name=return" json:"return,omitempty"`
	Destination *Path             `protobuf:"bytes,3,opt,name=destination" json:"destination,omitempty"`
	Payload     []byte            `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Metadata    map[string][]byte `protobuf:"bytes,5,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetOrigin() *Path {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *Message) GetReturn() *Path {
	if m != nil {
		return m.Return
	}
	return nil
}

func (m *Message) GetDestination() *Path {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Message) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetMetadata() map[string][]byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Path struct {
	Route    string             `protobuf:"bytes,1,opt,name=route" json:"route,omitempty"`
	Type     Path_ConnectorType `protobuf:"varint,2,opt,name=type,enum=pb.Path_ConnectorType" json:"type,omitempty"`
	Identity string             `protobuf:"bytes,3,opt,name=identity" json:"identity,omitempty"`
	Metadata map[string][]byte  `protobuf:"bytes,4,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Path) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Path) GetType() Path_ConnectorType {
	if m != nil {
		return m.Type
	}
	return Path_HTTP
}

func (m *Path) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *Path) GetMetadata() map[string][]byte {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Flow struct {
	Id             int64   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name           string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description    string  `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Path           *Path   `protobuf:"bytes,4,opt,name=path" json:"path,omitempty"`
	DependentFlows []*Flow `protobuf:"bytes,5,rep,name=dependentFlows" json:"dependentFlows,omitempty"`
	Wait           bool    `protobuf:"varint,6,opt,name=wait" json:"wait,omitempty"`
	Listen         bool    `protobuf:"varint,7,opt,name=listen" json:"listen,omitempty"`
}

func (m *Flow) Reset()                    { *m = Flow{} }
func (m *Flow) String() string            { return proto.CompactTextString(m) }
func (*Flow) ProtoMessage()               {}
func (*Flow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Flow) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Flow) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Flow) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Flow) GetPath() *Path {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *Flow) GetDependentFlows() []*Flow {
	if m != nil {
		return m.DependentFlows
	}
	return nil
}

func (m *Flow) GetWait() bool {
	if m != nil {
		return m.Wait
	}
	return false
}

func (m *Flow) GetListen() bool {
	if m != nil {
		return m.Listen
	}
	return false
}

func init() {
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*Path)(nil), "pb.Path")
	proto.RegisterType((*Flow)(nil), "pb.Flow")
	proto.RegisterEnum("pb.Path_ConnectorType", Path_ConnectorType_name, Path_ConnectorType_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x5d, 0x6b, 0xdb, 0x30,
	0x14, 0x9d, 0x3f, 0xe2, 0xd8, 0x37, 0x4d, 0x30, 0x97, 0x51, 0xbc, 0xb2, 0x07, 0x93, 0xa7, 0xd0,
	0x07, 0x33, 0x32, 0x06, 0xa3, 0x7b, 0xca, 0x3e, 0xca, 0xa0, 0x0b, 0x74, 0xc2, 0x7f, 0x40, 0xa9,
	0x45, 0x2b, 0x96, 0x48, 0x42, 0xbe, 0x59, 0xf1, 0x2f, 0xd8, 0xf3, 0xfe, 0xd5, 0x7e, 0xd6, 0x90,
	0xec, 0x66, 0x69, 0xde, 0xf7, 0x76, 0xcf, 0xb9, 0x47, 0xba, 0xf7, 0xe8, 0x08, 0xa6, 0x3b, 0xd1,
	0xb6, 0xfc, 0x5e, 0x54, 0xc6, 0x6a, 0xd2, 0x18, 0x9a, 0xcd, 0xfc, 0x57, 0x08, 0xe3, 0x75, 0xcf,
	0x62, 0x09, 0x89, 0xb6, 0xf2, 0x5e, 0xaa, 0x22, 0x28, 0x83, 0xc5, 0x64, 0x99, 0x56, 0x66, 0x53,
	0xdd, 0x72, 0x7a, 0x60, 0x03, 0xef, 0x14, 0x56, 0xd0, 0xde, 0xaa, 0x22, 0x3c, 0x55, 0xf4, 0x3c,
	0x5e, 0xc2, 0xa4, 0x11, 0x2d, 0x49, 0xc5, 0x49, 0x6a, 0x55, 0x44, 0x27, 0xb2, 0xe3, 0x26, 0x16,
	0x30, 0x36, 0xbc, 0xdb, 0x6a, 0xde, 0x14, 0x71, 0x19, 0x2c, 0xce, 0xd8, 0x13, 0xc4, 0x77, 0x90,
	0xee, 0x04, 0xf1, 0x86, 0x13, 0x2f, 0x46, 0x65, 0xb4, 0x98, 0x2c, 0x5f, 0xb9, 0x2b, 0x86, 0x45,
	0xab, 0xf5, 0xd0, 0xfb, 0xa2, 0xc8, 0x76, 0xec, 0x20, 0xbd, 0xf8, 0x00, 0xd3, 0x67, 0x2d, 0xcc,
	0x21, 0xfa, 0x21, 0x3a, 0x6f, 0x27, 0x63, 0xae, 0xc4, 0x97, 0x30, 0xfa, 0xc9, 0xb7, 0x7b, 0xe1,
	0x0d, 0x9c, 0xb1, 0x1e, 0x5c, 0x85, 0xef, 0x83, 0xf9, 0xef, 0x10, 0x62, 0xb7, 0xa3, 0x93, 0x58,
	0xbd, 0x27, 0x31, 0x1c, 0xeb, 0x01, 0x5e, 0x42, 0x4c, 0x9d, 0xe9, 0xcf, 0xcd, 0x96, 0xe7, 0x4f,
	0x8e, 0xaa, 0x4f, 0x5a, 0x29, 0x71, 0x47, 0xda, 0xd6, 0x9d, 0x11, 0xcc, 0x6b, 0xf0, 0x02, 0x52,
	0xd9, 0x08, 0x45, 0x92, 0x3a, 0xff, 0x02, 0x19, 0x3b, 0x60, 0x5c, 0x1e, 0x59, 0x8b, 0xbd, 0xb5,
	0x7f, 0x77, 0xfd, 0x17, 0x5f, 0x57, 0x30, 0x7d, 0xb6, 0x23, 0xa6, 0x10, 0x7f, 0xad, 0xeb, 0xdb,
	0xfc, 0x85, 0xab, 0xd6, 0xdf, 0xeb, 0x3a, 0x0f, 0x30, 0x83, 0xd1, 0xcd, 0xea, 0xfa, 0x66, 0x95,
	0x87, 0x08, 0x90, 0x7c, 0x5b, 0xad, 0x3f, 0x7e, 0x5e, 0xe5, 0xd1, 0xfc, 0x4f, 0x00, 0xf1, 0xf5,
	0x56, 0x3f, 0xe2, 0x0c, 0x42, 0xd9, 0xf8, 0x79, 0x11, 0x0b, 0x65, 0x83, 0x08, 0xb1, 0xe2, 0xbb,
	0x7e, 0x5a, 0xc6, 0x7c, 0x8d, 0xa5, 0x8f, 0xfe, 0xce, 0x4a, 0x73, 0x88, 0x3e, 0x63, 0xc7, 0x14,
	0xbe, 0x86, 0xd8, 0x70, 0x7a, 0xf0, 0x69, 0x1f, 0xff, 0x0a, 0xcf, 0xe2, 0x1b, 0x98, 0x35, 0xc2,
	0x08, 0xe5, 0x5e, 0xca, 0x0d, 0x6d, 0x87, 0xe8, 0xbd, 0xce, 0x11, 0xec, 0xa4, 0xef, 0xb6, 0x78,
	0xe4, 0x92, 0x8a, 0xa4, 0x0c, 0x16, 0x29, 0xf3, 0x35, 0x9e, 0x43, 0xb2, 0x95, 0x2d, 0x09, 0x55,
	0x8c, 0x3d, 0x3b, 0xa0, 0x4d, 0xe2, 0xff, 0xfc, 0xdb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0xff, 0x94, 0xd9, 0x04, 0x03, 0x00, 0x00,
}
